# Generated by Django 6.0.3 on 2026-04-05 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendancepolicy_leavetype_department_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Is 2FA currently enabled for this user')),
                ('secret_key', models.CharField(blank=True, help_text='Secret key for TOTP', max_length=255)),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='List of backup codes')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS 2FA', max_length=20)),
                ('is_sms_enabled', models.BooleanField(default=False, help_text='Is SMS-based 2FA enabled')),
                ('is_authenticator_enabled', models.BooleanField(default=False, help_text='Is authenticator app 2FA enabled')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When 2FA was last verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two Factor Authentication',
                'verbose_name_plural': 'Two Factor Authentications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login Attempt'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_verified', '2FA Verification Success'), ('2fa_failed', 'Failed 2FA Attempt'), ('backup_code_used', 'Backup Code Used'), ('session_created', 'Session Created'), ('session_expired', 'Session Expired'), ('permission_denied', 'Permission Denied'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('suspicious_activity', 'Suspicious Activity Detected'), ('logout', 'Logout')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Approximate location from IP', max_length=255)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='employees_s_user_id_2190dd_idx'), models.Index(fields=['event_type', 'created_at'], name='employees_s_event_t_82ab3b_idx'), models.Index(fields=['is_suspicious'], name='employees_s_is_susp_35aff3_idx')],
            },
        ),
    ]
